### ISSUE TITLE
FR: wrap() method for union types

### ISSUE THREAD

**Issue by mcintyret** [palantir/conjure-java#106]
Given the union type:
```
MyUnionType:
  union:
    type1: UnionType1
    type2: UnionType2
    type3: UnionType3
```
We could have `UnionType1`, `UnionType2` and `UnionType3` implement some interface, say
```
interface MyUnionTypeMember {
  MyUnionType wrapAsMyUnionType();
}
```
With implementations
```
class UnionType1 {
...
  MyUnionType wrapAsMyUnionType() {
    return MyUnionType.unionType1(this);
  }
}
```
etc.

I've come across a few cases now where this would have solved some boilerplate.

Granted there are some limitations - it wouldn't work for union members that are primitive types or imports - and it may not be worth the extra complexity. But worth a thought.
