### ISSUE TITLE
Generated object builders don't guard against method name conflicts

### ISSUE THREAD

**Issue by sfackler** [palantir/conjure-java#126]
Consider the following object definition:

```yaml
types:
  definitions:
    objects:
      ConflictedObject:
        foo: list<string>
        addAllFoo: list<string>
```

The generated Java implementation fails to compile, as the builder ends up with the following pair of methods:

```java
        public Builder addAllFoo(Iterable<String> foo) {
            ConjureCollections.addAll(this.foo, Objects.requireNonNull(foo, "foo cannot be null"));
            return this;
        }

        @JsonSetter("addAllFoo")
        public Builder addAllFoo(Iterable<String> addAllFoo) {
            this.addAllFoo.clear();
            ConjureCollections.addAll(
                    this.addAllFoo, Objects.requireNonNull(addAllFoo, "addAllFoo cannot be null"));
            return this;
        }
```

It seems like the first method's name should be munged in some way to avoid the conflict, like `addAllFoo_`.
