### ISSUE TITLE
compilation error when using optional alias integer query parameter

### ISSUE THREAD

**Issue by skedida** [palantir/conjure-java#1271]
## What happened?

Given a conjure definition:
```
types:
  definitions:
    default-package: com.example.api
    objects:

      MyParam:
        alias: integer

services:
  SomeExampleService:
    name: example
    package: com.example.api
    default-auth: header
    endpoints:
      getData:
        http: GET /something
        args:
          optionalIntParam:
            type: optional<MyParam>
            param-type: query
        returns: string
```

The generated `SomeExampleServiceEndpoints.GetDataEndpoint` class contains the following method
```
        @Override
        public void handleRequest(HttpServerExchange exchange) throws IOException {
            AuthHeader authHeader = runtime.auth().header(exchange);
            Map<String, Deque<String>> queryParams = exchange.getQueryParameters();
            OptionalInt optionalIntParamRaw =
                    runtime.plainSerDe().deserializeOptionalInteger(queryParams.get("optionalIntParam"));
            Optional<MyParam> optionalIntParam =
                    Optional.ofNullable(optionalIntParamRaw.isPresent() ? MyParam.of(optionalIntParamRaw.get()) : null); // This does not compile
            String result = delegate.getData(authHeader, optionalIntParam);
            serializer.serialize(result, exchange);
        }
```

This does not compile because `optionalIntParamRaw` does not have a `.get()` method and instead has `.getAsInt()` (see [javadocs](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/OptionalInt.html)) 

**Workaround**: Use `optional<integer>` instead of an alias

## What did you want to happen?
No compilation errors
