### ISSUE TITLE
Add strictUnions option

### ISSUE THREAD

**Issue by Diego-Zulu** [palantir/conjure-java#2498]
Right now Bean generation can be made strict via the `strictObjects` option. This means that, if this option is provided, [bean generator ](https://github.com/palantir/conjure-java/blob/c41ab46468f8b8844481f224f578af193e49eb29/conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanGenerator.java#L208-L210) and [build bean generator](https://github.com/palantir/conjure-java/blob/c41ab46468f8b8844481f224f578af193e49eb29/conjure-java-core/src/main/java/com/palantir/conjure/java/types/BeanBuilderGenerator.java#L443-L445) won't add the JsonIgnoreProperties decorator, which means deserialisation for these objects will fail if their definition contains unknown keys.

This option was not extended to union generators, so right now it is possible to commit accidental mistakes like:

```
my-union-type:
  type: first-type
  first-type:
    first-field: foo
  accidentally-indented-field: this should not be indented and sadly will be ignored because it is indented below a union type
```

To prevent this kind of accidental mistakes, it would be cool if we could have a new option `strictUnions` that would behave the same way as `strictObjects` but prevents the [union generator](https://github.com/palantir/conjure-java/blob/c41ab46468f8b8844481f224f578af193e49eb29/conjure-java-core/src/main/java/com/palantir/conjure/java/types/UnionGenerator.java#L704-L706)  from adding the JsonIgnoreProperties decorator.

I'll self assign this for now as I plan to take a stab at this and create a PR
