### ISSUE TITLE
Undocumented breaking change between 1.0.0 and 1.1.0 

### ISSUE THREAD

**Issue by mnazbro** [palantir/conjure-java#27]
There is an undocumented breaking change between 1.0.0 and 1.1.0 that causes any code that has query parameters appear before any required parameters to fail compilation. The easiest workaround is to reorder the parameters, however that can cause confusion to end users where the type safety may be weaker than in Java (aka TypeScript).

**Comment by mnazbro** [comment]
The workaround does not work. Here are examples:
Conjure:
```yaml
MyService:
    name: My service
    package: com.palantir.service
    base-path: /service
    default-auth: header
    endpoints:
      create:
        http: POST /{value1}
        args:
          value1:
            type: string
          query: Query
          token:
            type: optional<string>
            param-type: query
          compareDate:
            type: optional<Date>
            param-type: query
        returns: Response
```
Output:
```java
public interface Service {
    @POST
    @Path("service/{value1}")
    Response create(
            @HeaderParam("Authorization") AuthHeader authHeader,
            @PathParam("value1") String value1,
            @QueryParam("token") Optional<String> token,
            @QueryParam("compareDate") Optional<Date> compareDate,
            Query query);

    @Deprecated
    default Response create(AuthHeader authHeader, String value1, Query query) {
        return create(authHeader, value1, query, Optional.empty(), Optional.empty());
    }

    @Deprecated
    default Response create(
            AuthHeader authHeader, String value1, Optional<String> token, Query query) {
        return create(authHeader, value1, token, query, Optional.empty());
    }
}
```
