### ISSUE TITLE
Auto-fix type name 'Object'

### ISSUE THREAD

**Issue by iamdanfox** [palantir/conjure-java#32]
This should _not_ create a class called 'Object.java' otherwise it clashes horribly!

```yml
      Object:
        fields:
          string:
            type: string
```
