### ISSUE TITLE
Generated service interface does not compile when optional int query param is present

### ISSUE THREAD

**Issue by a-k-g** [palantir/conjure-java#43]
This is on 1.3.0.
```
search:
  http: POST /tables
  args:
    searchRequest:
      type: TableSearchRequest
    pagingToken:
      type: optional<PagingToken>
      param-type: query
    pageSize:
      type: optional<integer>
      param-type: query
      markers:
        - Safe
  returns: TableSearchResponse
```
generates 
```
@POST
@Path("search/tables")
TableSearchResponse search(
        @HeaderParam("Authorization") AuthHeader authHeader,
        @QueryParam("pagingToken") Optional<PagingToken> pagingToken,
        @QueryParam("pageSize") @Safe OptionalInt pageSize,
        TableSearchRequest searchRequest);

@Deprecated
default TableSearchResponse search(AuthHeader authHeader, TableSearchRequest searchRequest) {
    return search(authHeader, Optional.empty(), Optional.empty(), searchRequest);
}

@Deprecated
default TableSearchResponse search(
        AuthHeader authHeader,
        Optional<PagingToken> pagingToken,
        TableSearchRequest searchRequest) {
    return search(authHeader, pagingToken, Optional.empty(), searchRequest);
}
```

The generation of these `@Deprecated` methods seems new. They don't compile however, because they're delegating with `Optional.empty()` instead of `OptionalInt.empty()` for the `pageSize` query param.
