### ISSUE TITLE
A union type even in invalid format should deserialize to Unknown 

### ISSUE THREAD

**Issue by gm2211** [palantir/conjure-java#564]
## What happened?
Given:
```
    objects:
      Foo:
        fields:
          foo: string
      Bar:
        fields:
          bar: string
      FooBar:
        union:
          foo: Foo
          bar: Bar
```

the following fails:
```
        ObjectMapper mapper = ObjectMappers.createDefaultJsonObjectMapper(false);
        String good = "{\n"
                + "  \"type\" : \"bar\",\n"
                + "  \"bar\" : {\n"
                + "    \"bar\" : \"123\"\n"
                + "  }\n"
                + "}";
        String bad = "{\n"
                + "  \"type\" : \"new\",\n"
                + "  \"some-string\""
                + "}";

        assertThat(mapper.readValue(good, FooBar.class))
                .extracting("value")
                .extracting("value")
                .isInstanceOf(Bar.class);
        assertThat(mapper.readValue(bad, FooBar.class))
                .extracting("value")
                .extracting(Object::getClass)
                .extracting(Class::getSimpleName)
                .asString()
                .contains("UnknownWrapper");
```

## What did you want to happen?

The test should pass.

We can achieve this by modifying the generated code for the unknown wrapper to look something like this:

![image](https://user-images.githubusercontent.com/1555460/65095931-27a32780-d991-11e9-8cdc-233904aa0396.png)

this is obviously not completely correct since if `type` is missing or there exists no sub-object, we'd be setting the raw invalid json as `type`, so we'd probably have to do a little more work (like making `type` optional or nullable for the unknown wrapper)
