### ISSUE TITLE
Serialization of Object as Key in Map becomes Nested

### ISSUE THREAD

**Issue by brikeohane** [palantir/conjure-java#605]
## What happened?

Seeing issues with serialization in Undertow. For a service, I have the following conjure objects defined (names have been changed to hide details of service):
```yaml
SingleResultKey:
  fields:
    name: string

SingleResult:
  fields:
    objectMap: map<SingleResultKey, string>

Response:
  alias: list<SingleResult>
```

The `Response` is returned from a service call. Tracing through in the debugger, everything works correctly until the serialization in the generated UndertowService class. I expect the top result, but the 2nd one is returned: 

Before serialization: `[SingleResult{objectMap: {SingleResultKey{name: TEST}=answer}}]`

After serialization: `[SingleResult{objectMap: SingleResultKey{name: SingleResultKey{name: TEST}}=answer}}}]`

So SingleResultKey (the key in the map) became a nested object on a call to `Serializer.serialize(result, exchange)` within the UndertowService. This fails for server tests and when debugging in intellij, but a curl to the running service produces the correct, non-nested output.

## What did you want to happen?

Produce the expected output and properly serialize the SingleResultKey as the key in the map.
