### ISSUE TITLE
Conjure-generated service does not start if endpoint contains certain alias definitions

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure-java#68]
Example input definition:

```
types:
  definitions:
    default-package: com.palantir.product
    objects:
      AliasOne:
        alias: string
      AliasTwo:
        alias: optional<AliasOne>
services:
  EteService:
    name: Ete Service
    package: com.palantir.product
    default-auth: header
    base-path: /base

    endpoints:
      optionalAliasOne:
        http: GET /optionalAliasOne
        args:
          queryParamName:
            param-type: query
            type: optional<AliasOne>
        returns: optional<AliasOne>

      aliasTwo:
        http: GET /aliasTwo
        args:
          queryParamName:
            param-type: query
            type: AliasTwo
        returns: AliasTwo
```

Note that, form a serialization/semantic standpoint, the `optionalAliasOne` and `aliasTwo` are equivalent.

However, attempting to start a Conjure-generated server with these definitions fails with the following exception:

```
Caused by: org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[FATAL] No injection source found for a parameter of type public com.palantir.product.AliasTwo com.palantir.conjure.java.EteResource.aliasTwo(com.palantir.tokens.auth.AuthHeader,com.palantir.product.AliasTwo) at index 1.; source='ResourceMethod{httpMethod=GET, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.palantir.conjure.java.EteResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@6ac4c3f7]}, definitionMethod=public abstract com.palantir.product.AliasTwo com.palantir.product.EteService.aliasTwo(com.palantir.tokens.auth.AuthHeader,com.palantir.product.AliasTwo), parameters=[Parameter [type=class com.palantir.tokens.auth.AuthHeader, source=Authorization, defaultValue=null], Parameter [type=class com.palantir.product.AliasTwo, source=queryParamName, defaultValue=null]], responseType=class com.palantir.product.AliasTwo}, nameBindings=[]}']
```

If the `aliasTwo` endpoint is commented out, the server starts up as expected.

The `aliasTwo` types and definitions should be legal per the Conjure spec, so the Java generator creating a server that does not start based on these valid definitions is a bug.
