### ISSUE TITLE
Conjure-generated client does not properly serialize nested aliases in PLAIN context

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure-java#70]
Generate a Conjure client using the following definition:

```
types:
  definitions:
    default-package: com.palantir.product
    objects:
      AliasOne:
        alias: string
      AliasTwo:
        alias: optional<AliasOne>
      AliasThree:
        alias: AliasTwo

services:
  EteService:
    name: Ete Service
    package: com.palantir.product
    base-path: /base

    endpoints:
      aliasThree:
        http: GET /aliasThree
        args:
          queryParamName:
            param-type: query
            type: AliasThree
        returns: AliasThree
```

Make the following client call:

```
eteService.aliasThree(AliasThree.of(AliasTwo.of(Optional.empty()))
```

Expected
----------
Calls the endpoint with no query parameters (because serialized equivalent is `Optional.empty()`)

Actual
-------
Calls the endpoint with a query parameter that consists of the literal string `Optional.empty`

The same issue exists for non-optional calls:

```
eteService.aliasThree(
                AliasThree.of(AliasTwo.of(Optional.of(AliasOne.of("hello"))))
```

Expected
----------
Query parameter value is `hello`

Actual
------
Query parameter value is `Optional[hello]`

----

Based on this, it appears that PLAIN serialization does not properly work for alias types nested in optionals.
