### ISSUE TITLE
Unexpected behavior of optional error args

### ISSUE THREAD

**Issue by derouinw** [palantir/conjure-java#782]
## What happened?

When an error type includes an optional arg, it will return a string with `"Optional"` in it: `"Optional.empty"` or `"Optional[value]"`.

### Example
Conjure definition:
```yaml
types:
  definitions:
    errors:
      BadThing:
        namespace: Demo
        code: NOT_FOUND
        docs: A Bad Thing happened
        safe-args:
          objectRid: optional<rid>
```
```ts
export interface IBadThing {
    'errorCode': "NOT_FOUND";
    'errorInstanceId': string;
    'errorName': "Demo:BadThing";
    'parameters': {
        objectRid: string | null;
    };
}
export declare function isBadThing(arg: any): arg is IBadThing;
```
Throw in java:
```java
DemoErrors.throwBadThingException(Optional.empty());
DemoErrors.throwBadThingException(Optional.of(ResourceIdentifier.valueOf("ri.resource.demo.test.123-456"));
```
JSON response:
```json
{
    "errorCode": "NOT_FOUND",
    "errorName": "Demo:BadThing",
    "errorInstanceId": "...",
    "parameters": {
        "objectRid": "Optional.empty"
    }
}
{
    "errorCode": "NOT_FOUND",
    "errorName": "Demo:BadThing",
    "errorInstanceId": "...",
    "parameters": {
        "objectRid": "Optional[ri.resource.demo.test.123-456]"
    }
}
```
## What did you want to happen?
Since the generated typings call for `string | null`, I would expect the parameter to be just the value or either missing or `null` when returned. 

This seems to be due to `logsafe` behavior of just calling `toString` on whatever is passed into a `SafeArg`. On the `conjure-java` side, this could maybe be implemented by unwrapping the optional - taking the value if present or skipping the arg if empty. However, I'm not sure what the impact would be to existing consumers that depend on this behavior.
